name: Karma Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Job Setup
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #Checkout Repo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run Karma Tests
      run: |
        npm install
        npm run test  